apiVersion: v1
kind: Service
metadata:
  name: pubsub
  labels:
    app: pubsub
spec:
  externalName: pubsub
  type: NodePort
  ports:
    - name: pubsub
      port: 8681
      nodePort: 30100
  selector:
    app: pubsub
